---
- name: Atualizar repositórios (apt-get update) se a última atualização foi a mais de 1h
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar Discord
  ansible.builtin.apt:
    deb: https://discord.com/api/download?platform=linux&format=deb

- name: Instalar Google Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Instalar Visual Studio Code
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Adicionar repositório qBittorrent
  ansible.builtin.apt_repository:
    repo: 'ppa:qbittorrent-team/qbittorrent-stable'
    codename: jammy

- name: Instalar dependência para repositório Neovim
  ansible.builtin.apt:
    name: software-properties-common
    state: present
- name: Adicionar repositório Neovim
  ansible.builtin.apt_repository:
    codename: jammy
    repo: ppa:neovim-ppa/stable

- name: Atualizar repositórios (apt-get update)
  ansible.builtin.apt:
    update_cache: true

- name: Instalar programas CLI
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - exa
      - fzf
      - git
      - htop
      - neovim
      - openssh-server
      - tmux
      - zsh
    state: present

- name: Instalar programas GUI
  ansible.builtin.apt:
    name:
      - qbittorrent
      - vlc
    state: present
