---
# - name: Atualizar lista de pacotes (apt-get update) se a última atualização foi a mais de 1 hora
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600

- name: Adicionar repositório qBittorrent
  ansible.builtin.apt_repository:
    repo: 'ppa:qbittorrent-team/qbittorrent-stable'

- name: Atualizar lista de pacotes (apt-get update)
  ansible.builtin.apt:
    update_cache: true

- name: Instalar Discord
  ansible.builtin.apt:
    deb: https://discord.com/api/download?platform=linux&format=deb

- name: Instalar Google Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Instalar Visual Studio Code
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Instalar programas CLI
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - exa
      - fzf
      - git
      - htop
      - neovim
      - openssh-server
      - pipx
      - python3-tk
      - python3-venv
      - tmux
      - zsh
    state: present

- name: Instalar programas GUI
  ansible.builtin.apt:
    name:
      - qbittorrent
      - vlc
    state: present
