---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
    state: present

- name: Download asdf from git
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ home }}/.asdf"
    version: 'v0.14.1'
